# 端口
server:
  port: 7000

spring:
  application:
    name: config-git-server # 应用名称
  cloud:
    config:
      server:
        git:
          # 仓库地址
          uri: https://github.com/OJT112233/springcloud-config.git
          # 对应 {label} 部分，即 Git 的分支
          label: master
          #设置强行pull拉取
          force-pull: true
          # 仓库文件夹名称，多个以逗号分隔
          # search-paths: springcloud-config-git/config-repo
          # git 仓库用户名（公开库可以不用填写）
          # username:
          # git 仓库密码（公开库可以不用填写）
          # password:


eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30

